require 'json'
require 'redis'
require 'sinatra/base'
require './lib/redis_setting'
require_relative './helpers/main_helpers'
require_relative './controllers/application_controller'
require_relative './controllers/main_controller'
require_relative './controllers/robots_controller'
